### PR TITLE
Allow null values

### PR DESCRIPTION
**Pull request by orgads**
Align with protobuf IStruct, IListValue and IValue.

### CODE REVIEW

**Comment by callmehiphop** [comment]
Hi @orgads, could you point me in the direction of the documentation that supports this change? I was under the impression that this shouldn't be needed.

**Comment by orgads** [comment]
Actually I'm not sure if this is the right solution.

google-gax creates 2 types for each message: One interface with `I` prefix, in which every field has `|null`, and the other is a class without the prefix, and it doesn't have the `null`s.

See for example here: https://github.com/googleapis/gax-nodejs/blob/master/protos/iam_service.d.ts (search for `stringValue`).

Now, types refer to other types with their interface (I*), so if I refer to a nested type, it gets `|null`.

I got this issue with dialogflow.

Can you suggest a proper solution for that?

**Comment by orgads** [comment]
We need to improve coverage again 😒

**Comment by callmehiphop** [comment]
I could be wrong, but I think this types get pulled from [protobuf.js](https://github.com/protobufjs/protobuf.js/blob/42f49b43f692c24c2bc1ae081b4d1ad9fa173cd7/index.d.ts#L38), which doesn't have the `| null` type. I actually don't see any references to structs, values or lists in the IAM file you linked, they look like types with similar keys. 

Would you be able to provide some sample code that demonstrates your issue?

**Comment by orgads** [comment]
Sure: https://raw.githubusercontent.com/googleapis/nodejs-dialogflow/master/protos/protos.d.ts (notice it's a large file)

Search for `IValue` or `IStruct {`.

**Comment by callmehiphop** [comment]
I'm going to close this. I think what most users are doing is simply casting the values as `IStruct`, etc. If you feel like I'm making a mistake, let me know and we can discuss it further!

**Pull request closed without merging**
